This diagram has been generated with go-structurizr 
[https://github.com/krzysztofreczek/go-structurizr]
@startuml

title Todo service components

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction

scale 4096 width

skinparam rectangle<<_GROUP>> {
  FontColor #ffffff
  BorderColor #ffffff
}

skinparam artifact<<ADAPTER>> {
  BackgroundColor #2d69b7
  FontColor #ffffff
  BorderColor #000000
}

skinparam usecase<<DOMAIN>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
}

skinparam database<<INFRASTRUCTURE>> {
  BackgroundColor #c8c8c8
  FontColor #000000
  BorderColor #000000
}

rectangle 0ADAPTER <<_GROUP>> {
	artifact "==adapter.TodoResource\n<size:10>[component]</size>\n\nadapter component" <<ADAPTER>> as 2945167943
}
rectangle 29451679431DOMAIN <<_GROUP>> {
	usecase "==domain.TodoService\n<size:10>[component]</size>\n\ndomain component" <<DOMAIN>> as 2389247773
}
2945167943 .[#000000].> 2389247773 : ""
rectangle 23892477732INFRASTRUCTURE <<_GROUP>> {
	database "==infrastructure.TodoFakeRepository\n<size:10>[component]</size>\n\ninfrastructure component" <<INFRASTRUCTURE>> as 3040447786
}
2389247773 .[#000000].> 3040447786 : ""
rectangle 23892477732DOMAIN <<_GROUP>> {
	usecase "==domain.Todo\n<size:10>[component]</size>\n\ndomain component" <<DOMAIN>> as 2365432198
}
2389247773 .[#000000].> 2365432198 : ""
3040447786 .[#000000].> 2365432198 : ""
@enduml
